# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-09 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DucksInjury',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published', models.BooleanField(default=False)),
                ('last_injury', models.DateTimeField(default=datetime.datetime.now)),
                ('news_link', models.CharField(default=b'', max_length=150)),
                ('news_updates', models.TextField(default=b'There are no updates at this time.')),
                ('description', models.TextField(blank=True)),
                ('headline', models.CharField(default=b'<django.db.models.fields.DateTimeField>', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DucksPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Undefined', max_length=100)),
                ('position', models.CharField(default=b'None', max_length=15)),
                ('salary', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('healthy', models.BooleanField(default=False)),
                ('injury_type', models.CharField(default=b'N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=250)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.CharField(default=b'DQWL', max_length=4, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_string', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'EC - Sotiyo', b'EC - Sotiyo'), (b'EC - Azbel', b'EC - Azbel'), (b'EC - Raitaru', b'EC - Raitaru'), (b'Cit - Keepstar', b'Cit - Keepstar'), (b'Cit - Fortizar', b'Cit - Fortizar'), (b'Cit - Astrahus', b'Cit - Astrahus')], max_length=20)),
                ('system', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.CharField(max_length=30)),
                ('timer_ends_at', models.DateTimeField(default=datetime.datetime(2019, 4, 9, 18, 59, 54, 321767))),
            ],
        ),
        migrations.AddField(
            model_name='pollchoice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='milk.PollQuestion'),
        ),
        migrations.AddField(
            model_name='ducksinjury',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='milk.DucksPlayer'),
        ),
    ]
