# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0002_timer_timer_ends_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DucksInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_injury', models.DateTimeField(default=datetime.datetime(2017, 11, 3, 11, 0, 59, 700812))),
            ],
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 15, 0, 59, 700310)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='type',
            field=models.CharField(choices=[('EC - Sotiyo', 'EC - Sotiyo'), ('EC - Azbel', 'EC - Azbel'), ('EC - Raitaru', 'EC - Raitaru'), ('Cit - Keepstar', 'Cit - Keepstar'), ('Cit - Fortizar', 'Cit - Fortizar'), ('Cit - Astrahus', 'Cit - Astrahus')], max_length=20),
        ),
    ]
