# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0003_auto_20171103_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducksinjury',
            name='headline',
            field=models.CharField(default='<django.db.models.fields.DateTimeField>', max_length=150),
        ),
        migrations.AddField(
            model_name='ducksinjury',
            name='news_link',
            field=models.CharField(default='http://baggedmilk.me/wwdli', max_length=150),
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='last_injury',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 17, 38, 20, 821377)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 21, 38, 20, 820876)),
        ),
    ]
