# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0004_auto_20171103_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducksinjury',
            name='description',
            field=models.TextField(default='...'),
        ),
        migrations.AddField(
            model_name='ducksinjury',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='last_injury',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 13, 5, 5, 672767)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 17, 5, 5, 672767)),
        ),
    ]
