# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0005_auto_20171106_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ducksinjury',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='last_injury',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 13, 33, 42, 325127)),
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='news_link',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 17, 33, 42, 325127)),
        ),
    ]
