# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0006_auto_20171106_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducksinjury',
            name='news_updates',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='last_injury',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 18, 28, 51, 459870)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 22, 28, 51, 459369)),
        ),
    ]
