# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0007_auto_20171108_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ducksinjury',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='last_injury',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 13, 19, 59, 704570)),
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='news_updates',
            field=models.TextField(default='There are no updates at this time.'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 17, 19, 59, 704069)),
        ),
    ]
