# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0008_auto_20171121_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DucksPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undefined', max_length=100)),
                ('position', models.CharField(default='None', max_length=4)),
                ('salary', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('healthy', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='last_injury',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 28, 17, 38, 16, 802350)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 28, 21, 38, 16, 801347)),
        ),
        migrations.AddField(
            model_name='ducksinjury',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='milk.DucksPlayer'),
            preserve_default=False,
        ),
    ]
