# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0009_auto_20171128_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ducksinjury',
            name='last_injury',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 14, 54, 31, 975593)),
        ),
        migrations.AlterField(
            model_name='ducksinjury',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='milk.DucksPlayer'),
        ),
        migrations.AlterField(
            model_name='ducksplayer',
            name='position',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 18, 54, 31, 974590)),
        ),
    ]
