# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0010_auto_20171130_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ducksinjury',
            name='last_injury',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 18, 57, 51, 432390)),
        ),
    ]
