# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0011_auto_20171130_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducksplayer',
            name='injury_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 20, 19, 29, 58189)),
        ),
    ]
