# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0013_auto_20171214_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='id',
            field=models.CharField(default='XA2P', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 16, 36, 32, 400809)),
        ),
    ]
