# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0014_auto_20171214_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='milk.PollQuestion'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='id',
            field=models.CharField(default='B28F', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 22, 5, 39, 666835)),
        ),
    ]
